### ISSUE TITLE
Reciprocal Duty of Honesty for ordinary users?

### ISSUE THREAD

**Issue by jbradleychen** [w3ctag/privacy-principles#107]
Is there a reciprocal duty of honesty, by which users must be honest? How is a service to differentiate between user agents representing authentic humans, and user agents that impersonate humans for dishonest ends? What duty or responsibility do user agents have to present themselves in such a way that online services can differentiate authentic humans users from deceptive imposters? If we want a Web were non-trivial services can be provided to anonymous users, it will require a means to differentiate an anonymous user from a bot. This suggests to me a possible duty even for anonymous users.

**Comment by npdoty** [comment]
The task force considered this topic both in the sections on incorporating different privacy principles (which came out of conversations on privacy and safety #106) -- [Incorporating Different Privacy Principles](https://w3ctag.github.io/privacy-principles/#balancing) -- and on choosing information to present -- [Support Choosing Which Information to Present](https://w3ctag.github.io/privacy-principles/#support-choosing-info). 

On that latter point, our recommendation was to design APIs for the user agent not to assert or make promises on behalf of the user. And as one conclusion from that, services should include potential malice and deception from the user in threat modeling. 

This recommendation was driven both by privacy interests and out of pragmatism. In some cases users will choose the information they present in order to protect themselves; in other cases some users will do so maliciously. This document cannot effectively put obligations on users and would be especially ineffective in prescriptions to those acting maliciously. There will certainly be interests, including but not exclusively related to security and privacy, for various services about the content that users provide and their behavior. There is ongoing work on trying to develop functionality where others can provide assertions, rather than relying on the user or the user's agent to assert on their behalf.

**Comment by npdoty** [comment]
closing per task force discussions
