### ISSUE TITLE
Describe paradigms for data use

### ISSUE THREAD

**Issue by jyasskin** [w3ctag/privacy-principles#11]
I suspect we don't have consensus to pick one, but it seems useful to describe the paradigms (?) that govern how people think about data use. Some examples:

* Notice and consent
* [Contextual integrity](https://digitalcommons.law.uw.edu/wlr/vol79/iss1/10/)
* Does the GDPR's "data controller" vs "data processor" thing fit here?
* Personal data as "part" of a person (distilled from https://twitter.com/TrialByTruth/status/1402568590281392130; we probably want to find a paper about this in order to cite it)

**Comment by darobin** [comment]
I don't think that these are all at the same level.

The GDPR's controller vs processor is arguably the closest analogue to a notion of ownership (at least by processing entities) for something that can be endlessly copied. You are a controller when you determine the means and purposes of what can be done with the data you hold. It's an important distinction at several levels (and it's not really GDPR-specific, there are conceptually comparable ideas eg. in the CCPA). For one, the privacy properties are not the same if the party you are interacting with passes the data to an entity that essentially just works for that party (and is sort of an implementation detail, as it were) or if they pass the data to an entity that can determine its own purposes. (That's why I spent time defining means and purposes; these are important building blocks.) Another important aspect of the processor/controller distinction is that it has an impact on the health of the data economy. There has been a continuous shift from the first party being the sole controller (what is know as the _Vegas Rule_ or the _Drummond Doctrine_, because it used to be Google's position as voiced by Drummond at the time) to third parties asserting rights to reuse data independently, and that is probably an issue we should consider in terms of stewardship of the Web.

Personal data as part of a person is what is know as the dignitarian view. (It's the view espoused in the EU charter.) It's explained notably in https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3727562. It's possible to write up interesting concepts and threats for both the dignitarian and propertarian views (as well as why they are both insufficient, as Viljoen explains).

The dignitarian view has interesting properties, for instance if you ask for someone's gender but only provide a binary option that may not match them then that is a violation of personality rights attached to their data, since it prevents data self-determination. So there are things that can be said based on that for Web content (though not necessarily things that can easily be automatically enforced). The propertarian view tends to be a big train wreck, but it could be interesting to summarise why.

Notice & choice is less a way of thinking about data than it is a procedural way for claiming compliance that companies like because it is easy to scale and tends to reduce people's agency. It works in some contexts (eg. experiments on human subjects when you can have a grad student take the time to obtain informed consent) but in general it's sham (see eg. https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3370433) and is dangerous for generally the same reasons that prompts are. A good way to think of it is that it's the ActiveX security model brought to privacy.

But none of these are mutually exclusive. The Contextual Integrity framework is designed precisely so that privacy situations can be described in a clear way and decisions can then be made about whether they are appropriate or what would need to change. All of the above are just variables in a CI framework. If you look at https://darobin.github.io/pup/#dfn-context for a very short reference:

* Controller vs processor is a transmission principle.
* Notice & choice too, and the details of how that transmission principle applies will matter a lot here.
* Dignitarian vs propertarian is largely going to be a context-relative norm.

That's why I like CI: it's not a paradigm, it's a method for describing privacy contexts that is clear and powerful. It's not opinionated, which means that you could describe even the worst data practices and come up with a norm that says it's okay.

For an example of how that works, it's good to look at notice & choice. Basically, the tenet of people who think that notice & choice is the right way to think about data is that anything is consentable, largely in a uniform manner. Comparing this to permission prompts in general, we know that's not true: some things are definitely not consentable, or at least not at scale through a prompt UX. It's just too easy to trick people into triggering footguns. Using CI, you can have a nuanced appraisal of when consent works and when it doesn't. Given some kinds of actors and some kinds of attributes, if the consent is obtained using an agency-positive mechanism (eg. as part of filling out a form, never as a modal), then we can consider norms under which that is appropriate. We can also says that browsers _have_ to assume the worst-case scenarios in terms of attributes and actors, and therefore that there is arguably no norm under which some data flows will be appropriate (eg. identifiers to third parties).

To take a step back from what you list, though, pretty much most of the PUP document is written to address exactly this question. I'm definitely not saying that we have to take all of it as-is or whatnot, but I think it might be faster to start from the content that's there and mark up what's contentious or unclear rather than paraphrase each part in turn in an issue and then rewrite from scratch? :)

**Comment by torgo** [comment]
We discussed today Robin bringing some of what he wrote above into the draft.

**Comment by darobin** [comment]
Include _the right to be let alone_, the personality/dignitarian views, some of the more common ones.
