### ISSUE TITLE
Add a section on the rights of children and how to balance them with the rights of their parents

### ISSUE THREAD

**Issue by IreneKnapp** [w3ctag/privacy-principles#157]
There is a wide variety of surveillance technology today intended for use on children, by parents or other authorities. The vast majority of public-facing material which addresses the ethics around this technology does so purely with regard to the rights of *parents* to be notified, to consent, etc. Unfortunately, that's pretty much what the law says in most jurisdictions: Most legal rights pertaining to children are actually rights that their parents have.

As a queer person, I do not know that I would have survived to adulthood if the surveillance technology that exists today had been around when I was young. I think it would be amazing for this spec to have a section describing the concerns that can arise where rights of parents come into conflict with legal or moral rights of children, and to present a vocabulary that can be used when balancing those concerns.

This idea came up during a Twitter conversation, and I'm writing this issue in an attempt to capture the thought. Please feel free to ask clarifying questions and I'll try to elaborate. I also take no strong position on exactly what form the proposed write-up should take; I'm just trying to flag a gap that I see in what's there now.

**Comment by miguelandres** [comment]
As a fellow queer person raised in a heavily conservative environment I will echo these concerns

**Comment by npdoty** [comment]
Thanks for highlighting this! There are sections (not yet filled out) regarding guardians/device owners to try to capture some of the complexities in situations where a device is owned by someone and used by someone else, which is often an asymmetric power relation (including at least employer/employee, parent/child). And there was also interesting in writing principles specific to vulnerable people in general.

cc @hober

**Comment by jyasskin** [comment]
#2 has a bit of discussion on this, and the sections Nick mentioned are https://w3ctag.github.io/privacy-principles/#guardians-and-owners and https://w3ctag.github.io/privacy-principles/#vulnerable-people. But #2 is based on the idea that the parent owns the device the kid is using, which unifies the problem with other sorts of device ownership. The issue here is more about parental vs child rights that would be independent of what device the kid is using, which might justify using the vulnerable-people section instead.

Overall, here, I'd like us to follow the lead of folks who were hurt by their parents' surveillance, both those who have and who don't have children of their own.

Should we even talk about parents having _rights_ to data about their children? I know the law uses that framing, but we should, when we can identify a more accurate framing and it's not going to cause problems, use the accurate framing. I defer to the real experts in the space, but as an initial guess, I might suggest that children and other vulnerable people have a right to make informed decisions and exercise their autonomy, and a right to get appropriate help in doing so. And then parents and other guardians have an _obligation_ rather than a right to provide that help. The question of balancing parental vs child rights then becomes a question of how to help the guardians fulfil their obligations and help the children and vulnerable people decide that they need help from a different source. And from there, as a parent myself, I have more questions than answers...

**Comment by jyasskin** [comment]
I should ask directly here, @IreneKnapp, how would you balance things in this space? What should we write and who should we cite?

**Comment by IreneKnapp** [comment]
Thanks so much for that question! Let me talk with my friends a bit and get my thoughts together (and maybe some citations, if we're lucky). :)
