### ISSUE TITLE
Addition to data minimisation

### ISSUE THREAD

**Issue by darobin** [w3ctag/privacy-principles#171]
@kdenhartog had a good suggestion for text that would go into data min in #166, but that part of the PR needs more work so we're breaking it out here. The text is:

> In each of these [=contexts=] the UA should assume by default that the user
> wishes to present an [=identity=] with minimal unique characteristics to
> remain as private as possible on the web.

**Comment by kdenhartog** [comment]
For #166 there's a corresponding issue open to track that work in #163 which is what originally motivated that portion of text. #167 was originally separated out without an issue opened because I thought that portion of text would be less continuous then what's in #166. 

Do you mind if we combine this issue with #163 and keep discussions going there and #166 will be the corresponding PR that will close #163 and then we can close this one now?

**Comment by kdenhartog** [comment]
I think #191 would come close to closing this one out as well. The way in which it's written expounds on the idea I was trying to get at while keeping it more reasonable to the way UAs are actually being built these days. The one thing that might help improve it is to talk about how defaults should be configured a bit more. 

@npdoty I've added a suggestion to #191 that I think would close this one out if you think that aligns with your goals. To me, what I was trying to get added seems very well aligned with that new principle you've proposed.

**Comment by torgo** [comment]
We agreed today to close based on #191.
