### ISSUE TITLE
Need matching documents for other kinds of principles

### ISSUE THREAD

**Issue by jyasskin** [w3ctag/privacy-principles#228]
@jbradleychen points out that if the W3C endorses a privacy principles document without endorsing matching documents for [other important groups of principles](https://w3ctag.github.io/ethical-web-principles/), we risk over-indexing on privacy, and hurting compliance with those other principles.

We've discussed this problem in the past, and concluded that our task force can't do much about it on our own, but it's a real problem for the W3C choosing to endorse this document as a Statement on the timeline we want.

**Comment by darobin** [comment]
I hear the concern and I would certainly very very strongly encourage the various bodies we have working on principles to ship sooner rather than later. However, I think there are mitigating reasons that support shipping as soon as we can regardless:

* The Web standards community doesn't tend to pay that much attention to whether a document is approved or not. That's primarily a signal for outside parties (and even then). I don't believe that having one doc as a Statement and others as (mature) drafts will have a real differential impact on our work.
* Shipping one will encourage others to ship. We'll get to a state of multiple docs shipped faster by shipping independently than if we try to coordinate.

**Comment by jbradleychen** [comment]
I don't think one could reasonably demand that all related documents be presented simultaneously.
I do think, however, that it would be appropriate for every such doc to acknowledge the need for balance, and the risks that can arise when balance is lacking.

Imagine, for example, if a strong position was articulated on free expression, without a balancing position on privacy and safety. It would increase the risk that standards and norms advance the interests of advertisers, political causes, and other publishing interests without adequate consideration for the privacy and safety-related harms they could induce.

It seems clear that privacy is ahead of certain balancing concerns, in part due to robust support from certain businesses and governments, as well as specific privacy incidents and failures. It is less clear that privacy is more important than free expression, or public safety, or the public right-to-know, or the integrity of the web corpus, or other basic public goods. In the context of our duties to the public, what duty do we have to moderate the risk of such a lack of balance?

**Comment by jbradleychen** [comment]
Perhaps I can try to draft a statement regarding this need for balance. Unless something already exists to this effect.

**Comment by jyasskin** [comment]
Today's discussion pointed out that we have 

> "While it focuses on privacy, this should not be taken as an indication that privacy is always more important than other ethical web principles, and this document doesn't address how to balance the different ethical web principles if they come into conflict."

in https://w3ctag.github.io/privacy-principles/#how-this-document-fits-in at the very beginning of this document.

There are also a couple other documents in the works for the other areas:
* @rhiaro is working on https://w3ctag.github.io/societal-impact-questionnaire/.
* The TAG is organizing https://www.w3.org/2023/03/secure-the-web-forward/.
