### ISSUE TITLE
Sharing identity and reading history aren't purposes

### ISSUE THREAD

**Issue by jyasskin** [w3ctag/privacy-principles#229]
@michaelkleber points out that https://w3ctag.github.io/privacy-principles/#opt-in-out says
>  In specific cases, [people](https://w3ctag.github.io/privacy-principles/#dfn-individual) should be able to [consent](https://w3ctag.github.io/privacy-principles/#dfn-opt-in) to more sensitive [purposes](https://w3ctag.github.io/privacy-principles/#dfn-purpose), such as having their [identity](https://w3ctag.github.io/privacy-principles/#dfn-identity) recognised across contexts or their reading history shared with a company.

But there are many purposes for which one might recognize someone across contexts or share reading history with a company, and not all such purposes are "more sensitive". The document should pick out some particular purposes that need consent here.

**Comment by darobin** [comment]
I think that there may be easier fixes here:

1. `should be able to [consent](https://w3ctag.github.io/privacy-principles/#dfn-opt-in) to more sensitive **processing**, such as` yada yada
2. `should be able to [consent](https://w3ctag.github.io/privacy-principles/#dfn-opt-in) to more sensitive [purposes](https://w3ctag.github.io/privacy-principles/#dfn-purpose), such as **those that require** having their` yada yada

I don't think anyone likes it when we list purposes ranked by sensitivity?

**Comment by jyasskin** [comment]
The text about
> The burden of proof on ensuring that informed [consent](https://w3ctag.github.io/privacy-principles/#dfn-opt-in) has been obtained needs to be very high in this case.

is also an issue: this isn't a court case that has burdens of proof, and the possible purposes vary in how much the person ought to be informed before letting them consent. E.g. the purpose of "showing you pages you read recently" probably needs very little informing, while the purpose of "identifying people who are too woke to deserve a bank account" needs more.

**Comment by michaelkleber** [comment]
Suppose I read news articles on a site that only lets me read 5 per month without subscribing, and they remember which ones I've already read to enforce this cap.  Certainly a company is logging some history of what I've read, and there is some processing taking place.  But I don't think there is a particularly elevated sensitivity, a very high burden of proof, or anything going on that relates to opt-in vs opt-out.

As Jeffrey said in the title of this Issue, the elevated sensitivity seems to be more about the _purpose_ than about the data.  And the first graf of this section is indeed about purposes, while the third graf has pivoted away from that.

**Comment by darobin** [comment]
@michaelkleber I don't think that that's a correct data protection assessment. Data processing is treated as sensitive because of what it enables, not because of what is actually done. Say I collected the detailed biometrics of billions of people to make a beautiful work of art. Surely my purpose is innocuous, maybe even virtuous — but I'm still sitting on an insanely dangerous pile of data.

A site that keeps full history is keeping sensitive data. If it's only using it for paywall purposes, it should find a way to minimise that collection, get rid of it after a month, etc.

The purpose matters with respect to the person's preferences. Maybe you don't want to give me your DNA because you think my art sucks. But a purpose cannot be sensitive if the data collection isn't sensitive to start with. Much of the time, the agent cannot assess purposes but can assess some degree of risk.

**Comment by lknik** [comment]
> @michaelkleber I don't think that that's a correct data protection assessment. Data processing is treated as sensitive because of what it enables, not because of what is actually done. Say I collected the detailed biometrics of billions of people to make a beautiful work of art. Surely my purpose is innocuous, maybe even virtuous — but I'm still sitting on an insanely dangerous pile of data.

If we'd want to ground the discussion on some widely-accepted norms, we could cite the GDPR about 'processing: "_‘processing’ means any operation or set of operations which is performed on personal data or on sets of personal data, whether or not by automated means, such as collection, recording, organisation, structuring, storage, adaptation or alteration, retrieval, consultation, use, disclosure by transmission, dissemination or otherwise making available, alignment or combination, restriction, erasure or destruction_"

What you refer in the above (what it enables) is the _purpose_.

**Comment by michaelkleber** [comment]
> A site that keeps full history is keeping sensitive data. If it's only using it for paywall purposes, it should find a way to minimise that collection, get rid of it after a month, etc.

I completely agree!  But this is precisely my point: something like "only keep the count of unique readers" or "get rid of it after a month" is _still_ processing of that very same sensitive data, but for a highly privacy-beneficial purpose.

**Comment by lknik** [comment]
> > A site that keeps full history is keeping sensitive data. If it's only using it for paywall purposes, it should find a way to minimise that collection, get rid of it after a month, etc.
> 
> I completely agree! But this is precisely my point: something like "only keep the count of unique readers" or "get rid of it after a month" is _still_ processing of that very same sensitive data, but for a highly privacy-beneficial purpose.

It also sounds great! I hope that the principles/tag has the necessary remit to advice about it, as it is potentially about 1) back-end, 2) perhaps subject to legal constraints.

And indeed, keeping track/removing is _also_ processing.

**Comment by jyasskin** [comment]
I think #242 fixed this. Please re-open this if we got it wrong somehow.
