### ISSUE TITLE
Avoid endorsing cookie banners and other sharing indicators that encourage users to ignore them

### ISSUE THREAD

**Issue by jyasskin** [w3ctag/privacy-principles#230]
@michaelkleber points out that when https://w3ctag.github.io/privacy-principles/#opt-in-out says

> sharing data should be set up in such a way that it requires deliberate, specific action from the [person](https://w3ctag.github.io/privacy-principles/#dfn-individual) (eg. triggering a form control that is not on a modal dialog) and if that [consent](https://w3ctag.github.io/privacy-principles/#dfn-opt-in) is persistent, there should be a vivid indicator that data is being transmitted shown at all times, in such a way that the person can easily switch it off.

it endorses the [old browser popups asking about storing cookies](https://dada.cs.washington.edu/research/tr/2000/12/UW-CSE-00-12-03.pdf), and the new hated cookie banners on websites. UX research has shown that users get start ignoring notifications they see all the time, and if we're going to contradict it, we ought to cite something showing our advice is likely to be effective.

**Comment by dmarti** [comment]
What can we do to make it clearer that interrupting the user to get them to click a button they don't understand is not "consent" for purposes of this document?

Maybe we could use a term like "informed consent" for what we're now calling "consent", to make sure it's different from the meaningless interactions with "cookie banners"?

**Comment by lknik** [comment]
I agree that the text endorses cookie popups, whuch is of course in line with EU data protection law :) Specifically, so I would not call it _"old"_!

**Comment by michaelkleber** [comment]
Let's keep this issue focused on this recommendation about indicators that are "persistent" and "vivid" and "shown at all times".  This seems like a recipe for either a rage-inducing UX or else complete user blindness.  If we hope to have a doc that influences real behavior, then we should try to avoid strongly-worded recommendations that practitioners of the art will dismiss as ignoring decades of practical experience.

Don and Lukasz: I don't think the goal of this document includes the W3C picking a fight with the EU's data protection authorities over whether DPA-approved cookie banners comply with the Article 4(11) rules on consent ("freely given, specific, informed and unambiguous").  But in any case, feel free to open a different issue if you want to continue that argument.

**Comment by lknik** [comment]
@michaelkleber understood, OK. I'm just highlighting that it is unwise to standardise something going against clear and well understood legal requirements present in real-world settings _if that was the case_. If not, no problem.

**Comment by michaelkleber** [comment]
Yes, I agree, it seems like "Being Logged In" is a state that conventionally goes along with some persistent UI treatment, including showing your profile picture.  But this section seems to be talking about a much broader universe of processing that you might consent to, far beyond the idea of being logged into one account.

**Comment by npdoty** [comment]
Could include references on UX and consent fatigure, and also references to better forms of consent requests (making options equally accessible, etc.).

**Comment by darobin** [comment]
To be absolutely clear, the text is not intended to endorse banners or older cookie prompts. It is saying that sharing data should be an action, like triggering a form, and it specifically calls out `not on a modal dialog`. I also don't see why a persistent indicator that data is being shared would be rage-inducing. The login example is a good one: you could have a "data being shared" menu next to your face, unfolding it would list who it is being share with.

**Comment by michaelkleber** [comment]
I think I'm now more confused than when this discussion started.

The sentence in question reads:

> In the same way that it should be clear when a given device capability is in use (eg. you are providing geolocation or camera access), sharing data should be set up in such a way that it requires deliberate, specific action from the person (eg. triggering a form control that is not on a modal dialog) and if that consent is persistent, there should be a vivid indicator that data is being transmitted shown at all times, in such a way that the person can easily switch it off.

But to state the obvious, every page you load involves sharing some data (a URL, an IP address) with one or more servers.  My clicking on a link is a kind of subtle, easily-ignorable action by which I endorse this sharing, but it's absolutely not the kind of "deliberate, specific action" you're calling for here.  The browser's "loading" indicator shows that data is being transmitted, but it's not the "vivid indicator" you're asking for.  Reading or writing any cookie requires ePrivacy consent in the EU, but I don't think anyone wants every webpage to say "Reminder: the loading of this page _also_ involved sending our  cookies to our server."

In the ancient history of the web, browsers had a pop-up that asked for permission to store cookies, and it appeared on nearly every page load ([pix in Jeffrey's source](https://dada.cs.washington.edu/research/tr/2000/12/UW-CSE-00-12-03.pdf)).  That was indeed rage-inducing, and it was wisely removed from the UX, because having people click "ok" on a pervasive warning just to do what they were trying to do did not lead to heightened awareness but to warning blindness.

I want to make sure any UX suggestions here are plausible things that a browser or a site might actually follow, and right now I don't understand how this is.

**Comment by dmarti** [comment]
Another example not related to "logged in" state is [Jingjing and Chacha](https://en.wikipedia.org/wiki/Jingjing_and_Chacha). Animated police officers remind the users of government data collection on the web.

In cases where a private-sector party is collecting user data, they could also add an animated character to the page -- making a "vivid indicator" without requiring any action of the user.
