### ISSUE TITLE
Discuss multi-party consent

### ISSUE THREAD

**Issue by jyasskin** [w3ctag/privacy-principles#24]
Not feasible to get this consent in many cases, but some examples where more people are involved than just the end-user:
* Sharing my contacts reveals private information about the people in my contacts.
* Sharing my browsing history or information aggregated from it reveals information about the websites I visited.
* Sharing details of my life reveals information about people similar to me.

**Comment by dmarti** [comment]
Another example of a multi-party problem is the case where the user is consenting to use of their information by a controller that has information on lots of other people, and the valuable data is in the negative space -- people who do not have a particular quality.

 For example, if a user builds a profile on an ad-supported social site that reveals their interest in double-entry accounting, that information helps target investment scam ads that have a higher response rate among users with low accounting knowledge.

There is some kind of common problem here, where the user might want to disclose that they are a member of a high-information or high-status group, in order to push risks away from themselves and toward non-members of the group.

**Comment by darobin** [comment]
Fixed by #287. (@npdoty used "addresses" instead of "fixes" so it didn't auto-close)

**Comment by npdoty** [comment]
haha, Nick's careful verbosity strikes again
