### ISSUE TITLE
Please copy edit acting on data section

### ISSUE THREAD

**Issue by chaals** [w3ctag/privacy-principles#406]
The sentence

> If a [person](https://www.w3.org/TR/privacy-principles/#dfn-individual) could reasonably be identified or re-identified through the combination of [data](https://www.w3.org/TR/privacy-principles/#dfn-data) with other [data](https://www.w3.org/TR/privacy-principles/#dfn-data), then that [data](https://www.w3.org/TR/privacy-principles/#dfn-data) is [personal data](https://www.w3.org/TR/privacy-principles/#dfn-data).

is hard to understand, and in particular it is unclear what the final instance of "data" actually refers to.

**Comment by darobin** [comment]
Data data data data person data data data data data personal data. I don't see what the problem is @chaals.

Is this better: `If data could be combined with another data source to reasonably identify or re-identify someone, then that data is personal data.`?

**Comment by chaals** [comment]
The problem is identifying whether the thing described as personal data is the "data that could be combined", the "other data", both when combined, each of them individually *a priori*, or something else.

So no, rephrasing as

> If data could be combined with another data source to reasonably identify or re-identify someone, then that data is personal data.

doesn't solve the problem.

**Comment by jyasskin** [comment]
I think both the data and the other data each individually wind up being personal data, since "combining" is commutative on data. +1 that the phrasing is confusing. I also think the concept itself is confusing and not fully captured by any definition I've seen, since "the moon is round" can be combined with "Person X is Jeffrey Yasskin" to identify me. Since people with much greater expertise have failed to make this clear, I think we gave up on trying to do better than them.
