### ISSUE TITLE
Include origin sovereignty

### ISSUE THREAD

**Issue by darobin** [w3ctag/privacy-principles#79]
It would be interesting to add the principle that, to the extent that they can, user agents should enforce [origin sovereignty](https://github.com/darobin/Vision/blob/main/origin-sovereignty.md) as part of collective approaches to privacy. (See also mention in #77.)

**Comment by jyasskin** [comment]
Origin sovereignty, as proposed for the W3C's vision in https://github.com/WebStandardsFuture/Vision/pull/37, seems to have 3ish pieces, with varying connections to privacy. Paraphrasing:

1. ~"Aggregation and republishing are suspect." This seems like not a privacy issue, but rather a defense of a business model. I propose leaving this in the Vision document.
2. ~"Third parties must only be service providers." This is the topic of #77, and whatever principle we extract from that does belong here. I suspect the term "origin sovereignty" is going to confuse more than help on this point, so we should just state the principle.
3. ~"Website operators who also control other parts of the stack shouldn't compete unfairly." This is true, and perhaps connected to #78, in which privileged parts of the stack shouldn't use their customers' data in ways that aren't aimed enough at benefitting those customers.

You mention that origin sovereignty fits under "[collective approaches to privacy](https://w3ctag.github.io/privacy-principles/#collective)". If I'm understanding that section correctly, for it to fit there, you would have to mean that efforts to make websites collectively legible to their users—to categorize and systematize the websites—need to be governed democratically lest it violate those websites' rights. I don't think you do mean that, since it would invert the priority of constituencies.

**Comment by sandandsnow** [comment]
One of the challenges of using terms like "sovereignty" is that they already have a long history and even in new contexts evoke that history. Leaving aside the term, my concern is that the principle appears to take the perspective of the author (or operator of a Web property) and its needs, rather than of a user or users. We want user agents to protect users from malicious authors (operators of a Web property) that want to violate user privacy. But, perhaps I am not understanding how you intend to apply the principle in this context. Looking forward to discussion.

**Comment by wseltzer** [comment]
I also fear direct reference to "origin sovereignty" may bring in too many non-privacy points of not-yet-consensus.
