### ISSUE TITLE
Citation or reference for de-identified data

### ISSUE THREAD

**Issue by darobin** [w3ctag/privacy-principles#86]
@sandandsnow mentioned that she had some she could share.

**Comment by sandandsnow** [comment]
Here is a start:

There seem to be three approaches to describing de-identified data (1) the state or (2) the process (3) a combination of state and process. 

For a definition of “de-identified data”, this seems reasonable “a person’s identity is no longer apparent or cannot be reasonably ascertained from the information or data” (source: https://www.ipc.nsw.gov.au/fact-sheet-de-identification-personal-information). 

For a definition of “de-identification”, this seems reasonable: “a process by which a set of … data is altered, so that the resulting information cannot be readily associated with particular individuals” (source: https://www.ipc.nsw.gov.au/fact-sheet-de-identification-personal-information). For more detail about the process of de-identifying data, this also seems reasonable: “De-identification involves two steps. The first is the removal of direct identifiers. The second is taking one or both of the following additional steps: 
* the removal or alteration of other information that could potentially be used to re-identify an individual, and/or
* the use of controls and safeguards in the data access environment to prevent re-identification.” (source: https://www.oaic.gov.au/privacy/guidance-and-advice/de-identification-and-the-privacy-act)

The California Consumer Privacy Act 2018 uses this definition: “(h) “Deidentified” means information that cannot reasonably identify, relate to, describe, be capable of being associated with, or be linked, directly or indirectly, to a particular consumer, provided that a business that uses deidentified information:
(1) Has implemented technical safeguards that prohibit reidentification of the consumer to whom the information may pertain.
(2) Has implemented business processes that specifically prohibit reidentification of the information.
(3) Has implemented business processes to prevent inadvertent release of deidentified information.” (source: https://leginfo.legislature.ca.gov/faces/codes_displayText.xhtml?division=3.&part=4.&lawCode=CIV&title=1.81.5)

**Comment by npdoty** [comment]
FTC in 2012 had a similar combination definition:
> data is not "reasonably linked" if a company takes reasonable measures to de-identify the data, commits not to re-identify it, and prohibits downstream recipients from re-identifying it.


https://www.ftc.gov/news-events/press-releases/2012/03/ftc-issues-final-commission-report-protecting-consumer-privacy

I think the definitions that combine both state (identifiers and likely linkable connections) and process (prohibiting attempt to reidentify) are recognizing that it's difficult to know with certainty that a set of data can't be linked, as that depends not just on the data itself but also on the world of other datasets that can be potentially connected to it.
