### ISSUE TITLE
Definition of 'personal data'

### ISSUE THREAD

**Issue by mnot** [w3ctag/privacy-principles#92]
In Section 3, the document says:

> We define personal data as any information that is directly or indirectly about an identified or identifiable person, such as by reference to an identifier

This is *not* compatible with the GDPR's definition, which is:

> (1) 'personal data' means any information relating to an identified or identifiable natural person ('data subject')...

Note *about* vs *relating to*, which turns out to [matter](http://www8.austlii.edu.au/cgi-bin/viewdoc/au/cases/cth/FCAFC/2017/4.html) -- Australia is only recently [contemplating](https://consultations.ag.gov.au/rights-and-protections/privacy-act-review-discussion-paper/) a fix (see Section 2). You use 'indirectly', but it's not clear whether this changes the subject/object relationship of 'about'.

**Comment by mnot** [comment]
Also:

> If a person could reasonably be identified or re-identified when data is combined with other data, then that makes that data personal data.

is a bit meaningless; if I combine a phone book with a list of fruit at the local store, that makes the fruit personal data...

**Comment by jyasskin** [comment]
Am I right in reading paragraph 64 of http://www8.austlii.edu.au/cgi-bin/viewdoc/au/cases/cth/FCAFC/2017/4.html as saying that the court found that the information that "Mr Grubb has a red mobile phone" is not information "about" Mr Grubb? That seems like a silly decision. Or am I misunderstanding how they said "about" and "relating to" differ?

I pushed to replace "relating to" with "about" because "relating to" did seem too broad: the fact that Hawthorne Blvd has a speed limit of 25mph is "related to" me and lots of other people, but it doesn't seem like personal information. I'm sure it has a legal meaning in Europe that makes the whole definition make sense, but as this is not meant as a legal document, it didn't seem good to rely on a precise legal meaning to get our point across.

**Comment by mnot** [comment]
You are correct in that interpretation -- although calling a legal decision silly without all the context rarely works out well..

The world is pretty rapidly converging on at least the GDPR's definitions for various things about (hah!) privacy. It'd be a shame to work against that.

**Comment by darobin** [comment]
The second comment will be handled in #98.
