### ISSUE TITLE
"de-identification"

### ISSUE THREAD

**Issue by mnot** [w3ctag/privacy-principles#93]
"De-identification" often means merely removing identifiers and other information about a person.[^1] It also might include pseudonymisation. The GDPR refers to _anonymisation_ as the appropriate term;[^2] I'd suggest using it.

[^1]: _Privacy Act 1988_ (Cth) s 6(1).
[^2]: _GDPR_ (EU) rec 26.

**Comment by darobin** [comment]
We believe that _anonymisation_ is problematic because it often makes a promise that it often can't repay. The guidance on what GDPR means by anonymisation is pretty clear on the fact that it often doesn't mean anonymisation, which isn't great.

We're going to add a note discussion both terms and why we prefer one, for clarity.

**Comment by lknik** [comment]
The use of _anonymisation_ (also see [this](https://ec.europa.eu/justice/article-29/documentation/opinion-recommendation/files/2014/wp216_en.pdf), it may receive an update soon) is fine provided that it is clear what is meant under that term. But it should be linked with some kind of other definition like maybe 'personal data' (GDPR art 4(1): _‘personal data’ means any information relating to an identified or identifiable natural person_). The GDPR Recital 26's most important aspect is the "_singling out_" test, but I reckon a W3C document wouldn't want to go as deep as that. Is there a place for _pseudonymisation_?

**Comment by mnot** [comment]
If a term already has legal meaning, it might be best to purposefully use a different term.

**Comment by darobin** [comment]
This will be addressed in #86.
